[campaign]
name = "21_gridded_A_reg"
results_dir = "outputs/results_plots"

[run]
epochs_adam = 0
epochs_linesearch = 2000 # TODO : change name

rgi_ids = [
  "RGI60-11.02773"
]

[model]
invert_target = "A"
law_A = "CuffeyPatersonGridded"

[simulation]
gridScalingFactor = 3
tspan = [2010.0, 2011.0]
spinup = true
spinup_tspan = [2009.0, 2010.0]
step = 0.08333333333333333  # 1/12 for monthly
step_gt = 1.0