# Pertinent scenario set for 21_gridded_A_reg
# Lambda values:
# - H  = 8e36
# - V  = 3e37
# - HV = 3e37

[[scenarios]]
id = "S1"
loss_type = "H"
use_tim = false
sparsity_H = false
sparsity_V_sigma = 0.0
sparsity_V_threshold = 0.0
regularization_weight = 0.0

[[scenarios]]
id = "S2"
loss_type = "H"
use_tim = false
sparsity_H = false
sparsity_V_sigma = 0.0
sparsity_V_threshold = 0.0
regularization_weight = 8e36

[[scenarios]]
id = "S3"
loss_type = "V"
use_tim = false
sparsity_H = false
sparsity_V_sigma = 0.0
sparsity_V_threshold = 0.0
regularization_weight = 3e37